---
- hosts: app_services
  gather_facts: no
  any_errors_fatal: true
  vars_files: vars.yml
  tasks:
    - name: Build socialnetwork application
      shell: go build
      environment:
        PATH: $PATH:/usr/local/go/bin:/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/{{ hostvars[inventory_hostname]['user'] }}/.go/bin

    - name: Start socialnetwork app
      # /usr/bin/tmux new-session -s socialnetwork -d "export PATH=\$PATH:/usr/local/go/bin:/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/{{ hostvars[inventory_hostname]['user'] }}/.go/bin && weaver multi deploy weaver-gcp-eu.toml"
      shell: >
        /usr/bin/tmux new-session -s socialnetwork -d \
          "export PATH=$PATH:/usr/local/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/.go/bin && weaver multi deploy weaver-gcp-{{ hostvars[inventory_hostname]['region'] }}.toml"
      environment:
        PATH: $PATH:/usr/local/go/bin:/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/{{ hostvars[inventory_hostname]['user'] }}/.go/bin
      args:
        executable: /bin/bash
    
    - name: Verify if app is running
      wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        port: "{{ hostvars[inventory_hostname]['app_port'] | int }}"
        state: started
        timeout: 30
