# --------
# Services
# --------

["socialnetwork/services/ComposePostService"]
redis_address = "localhost"
redis_port = 6383
rabbitmq_address = "localhost"
rabbitmq_port = 5673
region = "us-central1"
regions = ["europe-west3", "us-central1"]

["socialnetwork/services/PostStorageService"]
mongodb_address = "localhost"
mongodb_port = 27018
region = "us-central1"

["socialnetwork/services/WriteHomeTimelineService"]
rabbitmq_address = "localhost"
rabbitmq_port = 5673
mongodb_address = "localhost"
mongodb_port = 27018
redis_address = "localhost"
redis_port = 6383
num_workers = 4
region = "us-central1"

["socialnetwork/services/UserTimelineService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27018

["socialnetwork/pkg/services/UrlShortenService"]
mongodb_address = "localhost"
mongodb_port = 27018

["socialnetwork/pkg/services/UserMentionService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27018

["socialnetwork/pkg/services/UserService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27018

["socialnetwork/pkg/services/SocialGraphService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27017

# ----------
# Deployment
# ----------

[single]
listeners.wrk2 = {address = "127.0.0.1:9001"}

[multi]
listeners.wrk2 = {address = "127.0.0.1:9001"}

[serviceweaver]
binary = "./socialnetwork"
name = "weaver-dsb-socialnetwork-us"

[gke]
regions = ["us-central1"]
listeners.wrk2 = {public_hostname = "weaver.dsb.socialnetwork"}
