# --------
# Services
# --------

["socialnetwork/pkg/services/ComposePostService"]
redis_address = "localhost"
redis_port = 6383
rabbitmq_address = "localhost"
rabbitmq_port = 5672
rabbitmq_username = "admin"
rabbitmq_password = "admin"
region = "europe-west3"
regions = ["europe-west3", "us-central1"]

["socialnetwork/pkg/services/PostStorageService"]
mongodb_address = "localhost"
mongodb_port = 27017
region = "europe-west3"

["socialnetwork/pkg/services/WriteHomeTimelineService"]
rabbitmq_address = "localhost"
rabbitmq_port = 5672
rabbitmq_username = "admin"
rabbitmq_password = "admin"
mongodb_address = "localhost"
mongodb_port = 27017
num_workers = 4
region = "europe-west3"

["socialnetwork/pkg/services/UserTimelineService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27017
region = "europe-west3"

# ----------
# Deployment
# ----------

[single]
listeners.wrk2 = {address = "127.0.0.1:9000"}

[multi]
listeners.wrk2 = {address = "127.0.0.1:9000"}

[serviceweaver]
binary = "./socialnetwork"
name = "weaver-dsb-socialnetwork-eu"

[gke]
regions = ["europe-west3"]
listeners.wrk2 = {public_hostname = "weaver.dsb.socialnetwork"}
