# --------
# Services
# --------

["socialnetwork/pkg/services/ComposePostService"]
redis_address       =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
rabbitmq_address    =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
redis_port          =  { "local" = 6381,        "europe-west3" = 6381,      "us-central-1" = 6385 }
rabbitmq_port       =  { "local" = 5672,        "europe-west3" = 5672,      "us-central-1" = 5673 }
regions             = ["europe-west3", "us-central1"]

["socialnetwork/pkg/services/HomeTimelineService"]
redis_address       =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
redis_port          =  { "local" = 6382,        "europe-west3" = 6382,      "us-central-1" = 6386 }

["socialnetwork/pkg/services/PostStorageService"]
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
memcached_address   =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }
memcached_port      =  { "local" = 11212,       "europe-west3" = 11212,     "us-central-1" = 11215 }

["socialnetwork/pkg/services/SocialGraphService"]
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
redis_address       =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
redis_port          =  { "local" = 6384,        "europe-west3" = 6384,      "us-central-1" = 6388 }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }

["socialnetwork/pkg/services/UrlShortenService"]
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
memcached_address   =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }
memcached_port      =  { "local" = 11213,       "europe-west3" = 11213,     "us-central-1" = 11216 }

["socialnetwork/pkg/services/UserService"]
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
memcached_address   =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }
memcached_port      =  { "local" = 11214,       "europe-west3" = 11217,     "us-central-1" = 11217 }

["socialnetwork/pkg/services/UserMentionService"]
# uses UserService cache (memcached)
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
memcached_address   =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }
memcached_port      =  { "local" = 11214,       "europe-west3" = 11217,     "us-central-1" = 11217 }

["socialnetwork/pkg/services/UserTimelineService"]
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
redis_address       =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }
redis_port          =  { "local" = 6383,        "europe-west3" = 6387,      "us-central-1" = 6387 }

["socialnetwork/pkg/services/WriteHomeTimelineService"]
# uses HomeTimelineService cache (redis)
rabbitmq_address    =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_address     =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
redis_address       =  { "local" = "localhost", "europe-west3" = "1.2.3.4", "us-central-1" = "4.3.2.1" }
mongodb_port        =  { "local" = 27017,       "europe-west3" = 27017,     "us-central-1" = 27018 }
redis_port          =  { "local" = 6382,        "europe-west3" = 6382,      "us-central-1" = 6386 }
rabbitmq_port       =  { "local" = 5672,        "europe-west3" = 5672,      "us-central-1" = 5673 }
num_workers         = 4

# ----------
# Deployment
# ----------

[single]
listeners.wrk2 = {address = "127.0.0.1:9000"}

[multi]
listeners.wrk2 = {address = "127.0.0.1:9000"}

[serviceweaver]
binary = "./socialnetwork"
name = "socialnetwork"

[gke]
regions = ["europe-west3", "us-central1"]
listeners.wrk2 = {public_hostname = "weaver.dsb.socialnetwork"}
