# --------
# Services
# --------

["socialnetwork/pkg/services/ComposePostService"]
redis_address = "localhost"
redis_port = 6383
rabbitmq_address = "localhost"
rabbitmq_port = 5673
region = "europe-west3"
regions = ["europe-west3", "us-central1"]

["socialnetwork/pkg/services/PostStorageService"]
mongodb_address = "localhost"
mongodb_port = 27017
region = "europe-west3"

["socialnetwork/pkg/services/WriteHomeTimelineService"]
rabbitmq_address = "localhost"
rabbitmq_port = 5672
mongodb_address = "localhost"
mongodb_port = 27017
redis_address = "localhost"
redis_port = 6383
num_workers = 4
region = "europe-west3"

["socialnetwork/pkg/services/HomeTimelineService"]
redis_address = "localhost"
redis_port = 6381

["socialnetwork/pkg/services/UserTimelineService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27017

["socialnetwork/pkg/services/UrlShortenService"]
mongodb_address = "localhost"
mongodb_port = 27017

["socialnetwork/pkg/services/UserMentionService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27017

["socialnetwork/pkg/services/UserService"]
redis_address = "localhost"
redis_port = 6383
mongodb_address = "localhost"
mongodb_port = 27017

["socialnetwork/pkg/services/SocialGraphService"]
redis_address = "localhost"
redis_port = 6380
mongodb_address = "localhost"
mongodb_port = 27017

# ----------
# Deployment
# ----------

[single]
listeners.wrk2 = {address = "127.0.0.1:9000"}

[multi]
listeners.wrk2 = {address = "127.0.0.1:9000"}

[serviceweaver]
binary = "./socialnetwork"
name = "weaver-dsb-db-eu"

[gke]
regions = ["europe-west3"]
listeners.wrk2 = {public_hostname = "weaver.dsb.socialnetwork"}
