---
- hosts: app_services
  gather_facts: no
  any_errors_fatal: true
  tasks:

    - name: Build socialnetwork application in app service nodes
      shell: go build
      args:
        chdir: "{{ app_folder_name }}"
      environment: # for Go and Weaver
        PATH: $PATH:/usr/local/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/.go/bin

    - name: Start socialnetwork app in app service nodes
      # /usr/bin/tmux new-session -s socialnetwork -d "export PATH=\$PATH:/usr/local/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/.go/bin && weaver multi deploy weaver-gcp-eu.toml"
      shell: >
        /usr/bin/tmux new-session -s socialnetwork -d \
          "export PATH=$PATH:/usr/local/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/.go/bin && weaver multi deploy weaver-gcp-{{ hostvars[inventory_hostname]['region'] }}.toml"
      args:
        executable: /bin/bash
        chdir: "{{ app_folder_name }}"
      environment: # for Go and Weaver
        PATH: $PATH:/usr/local/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/go/bin:/home/{{ hostvars[inventory_hostname]['user'] }}/.go/bin
    
    - name: Verify if app is running in app service nodes
      wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        port: "{{ hostvars[inventory_hostname]['app_port'] | int }}"
        state: started
        timeout: 30
